# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY *.go ./

RUN go build -o /docker-basic-web

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /docker-basic-web /docker-basic-web

EXPOSE 10000

USER nonroot:nonroot

ENTRYPOINT ["/docker-basic-web"]